- name: Create sysmon directory
  win_file:
    path: "{{ sysmon_install_location }}"
    state: directory

- name: Get sysmon zip
  win_get_url:
    url: "{{ sysmon_download_url }}"
    dest: "{{ sysmon_install_location }}"

- name: Unzip sysmon
  win_unzip:
    src: "{{ sysmon_install_location }}/Sysmon.zip"
    dest: "{{ sysmon_install_location }}"

- name: Remove sysmon zip
  win_file:
    path: "{{ sysmon_install_location }}/Sysmon.zip"
    state: absent

- name: Copy sysmon config
  win_get_url:
    url: "{{ sysmon_config_url }}"
    dest: c:\sysmon\sysmonconfig-export.xml
  register: sysmon_conf

- name: Run sysmon
  win_command: "{{ sysmon_install_location }}\\{{ sysmon_file_name }} -accepteula -i {{ sysmon_install_location }}\\sysmonconfig-export.xml"
  args:
    chdir: "{{ sysmon_install_location }}"

