---
# This task downloads and installs WinLogBeat with Malware Archeology config

- name: Get temp folder (because %temp% fails in win_find)
  win_tempfile:
    state: directory
  register: temp_folder

- debug:
    msg: "Temp folder path: {{ temp_folder.path }}"

- name: Get winlogbeat zip
  win_get_url:
    url: "{{ winlogbeat_download_url }}"
    dest: "{{ temp_folder.path }}/winlogbeat.zip"

- name: Unzip winlogbeat
  win_unzip:
    src: "{{ temp_folder.path }}/winlogbeat.zip"
    dest: "{{ temp_folder.path }}/winlogbeat_folders"

- name: Find unzip folder
  win_find:
    paths: ["{{ temp_folder.path }}/winlogbeat_folders"]
    recurse: false
    file_type: directory
  register: unzip_folder

- name: Copy directory
  win_copy:
    remote_src: true
    src: "{{ unzip_folder.files[0].path }}/"
    dest: "{{ winlogbeat_install_location }}"

- name: Copy WinLogBeat configuration.
  win_template:
    src: winlogbeat.yml.j2
    dest: "{{ winlogbeat_install_location }}/winlogbeat.yml"

- name: Install the service via script
  win_command: powershell.exe -ExecutionPolicy ByPass -File "{{ winlogbeat_install_location }}\install-service-winlogbeat.ps1"
  args:
    chdir: "{{ winlogbeat_install_location }}"

- name: Remove temp folder
  win_file:
    path: "{{ temp_folder.path }}"
    state: absent
